### ISSUE TITLE
VMware Tools

### ISSUE THREAD

**Issue by hadihashem** [FydeOS/overlay-variant-amd64-generic-vmware#8]
Hello
Can you please describe how to install VMware tools?
For the time being it looks to be not installed / activated as the following functions are not available:
- Network share
- Copy paste
- Screen resize...
Regards

**Comment by alphato-o** [comment]
VMWare Tools was not designed to work with unconventional Linux like Chromium OS, most of its features would not work including those you have mentioned. In order to achieve these functionalities, somebody will have to create a dedicated implementation of "helper" daemon. It's way beyond the purpose of this project.
